# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-10 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170210_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
