# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-12 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170212_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
