# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-09 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20170209_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learn_about',
            field=models.CharField(default='', max_length=200, verbose_name='\u901a\u8fc7\u672c\u8bfe\u7a0b\u540e\u80fd\u5b66\u5230\u7684'),
        ),
    ]
