# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-11 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20170209_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u5e7f\u544a\u4f4d'),
        ),
    ]
