# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-12 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20170211_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u5e7f\u544a\u4f4d'),
        ),
    ]
