# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-12 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20170212_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='\u7b2c\u4e00\u7ae0\uff1a', max_length=100, verbose_name='\u7ae0\u8282\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default='\u7b2c\u4e00\u8282\uff1a', max_length=100, verbose_name='\u89c6\u9891\u540d\u79f0'),
        ),
    ]
