# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170207_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5e74\u9f84'),
        ),
    ]
