# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-09 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='brief',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u673a\u6784\u7b80\u4ecb'),
        ),
    ]
