# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-10 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20170208_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='user',
            new_name='user_id',
        ),
    ]
